language: node_js
node_js:
  - "node"

# Use faster Docker architecture on Travis.
sudo: false

install:
  - yarn
  - node get-langs

cache: yarn

script:
  - node stop

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && node upload
